language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby
  - rbx
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"